apiVersion: apps/v1
kind: Deployment
metadata:
  generateName: deployment_name_prefix
  labels:
    app: ghost_namespace
spec:
  replicas: 1 # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: ghost_namespace
  template:
    metadata:
      labels:
        app: ghost_namespace
    spec:
      containers:
      - name: ghost
        image: ghost_image_tag
        env:
        - name: NODE_ENV
          value: development
        - name: database__connection__filename
          value: /var/lib/ghost/content/data/ghost.db
        ports:
        - containerPort: 2368
        volumeMounts:
        - name: ghost-data
          mountPath: /var/lib/ghost/content
      volumes:
      - name: ghost-data
        persistentVolumeClaim:
          claimName: ghost_data_pvc_ghost_namespace # Define your PVC or use an existing one
