# permissions for end users to view ghosts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: ghost-operator
    app.kubernetes.io/managed-by: kustomize
  name: ghost-viewer-role
rules:
- apiGroups:
  - blog.example.com
  resources:
  - ghosts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - blog.example.com
  resources:
  - ghosts/status
  verbs:
  - get
